// Code generated by "stringer -type=errType"; DO NOT EDIT.

package timespan

import "strconv"

const _errType_name = "noErrmisplacedSignErrmissingCoefErrunparseableCoefErrmissingMagErrunrecognizedMagErrmagnOrderUnkownErrmagnRestatedErrmagnOutOfOrderError"

var _errType_index = [...]uint8{0, 5, 21, 35, 53, 66, 84, 102, 117, 136}

func (i errType) String() string {
	if i < 0 || i >= errType(len(_errType_index)-1) {
		return "errType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errType_name[_errType_index[i]:_errType_index[i+1]]
}
